In [2]:
import pandas as pd
df=pd.read_csv("car.csv")
print(df.to_string())

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0                         ritz  2014           3.35          5.590       27000    Petrol      Dealer       Manual      0
1                          sx4  2013           4.75          9.540       43000    Diesel      Dealer       Manual      0
2                         ciaz  2017           7.25          9.850        6900    Petrol      Dealer       Manual      0
3                      wagon r  2011           2.85          4.150        5200    Petrol      Dealer       Manual      0
4                        swift  2014           4.60          6.870       42450    Diesel      Dealer       Manual      0
5                vitara brezza  2018           9.25          9.830        2071    Diesel      Dealer       Manual      0
6                         ciaz  2015           6.75          8.120       18796    Petrol      Dealer       Manual      0
7                      s cross  

In [2]:
print(pd.options.display.max_rows) 

60


In [3]:
pd.options.display.max_rows = 9999
print(df) 

                      Car_Name  Year  Selling_Price  Present_Price  \
0                         ritz  2014           3.35          5.590   
1                          sx4  2013           4.75          9.540   
2                         ciaz  2017           7.25          9.850   
3                      wagon r  2011           2.85          4.150   
4                        swift  2014           4.60          6.870   
5                vitara brezza  2018           9.25          9.830   
6                         ciaz  2015           6.75          8.120   
7                      s cross  2015           6.50          8.610   
8                         ciaz  2016           8.75          8.890   
9                         ciaz  2015           7.45          8.920   
10                    alto 800  2017           2.85          3.600   
11                        ciaz  2015           6.85         10.380   
12                        ciaz  2015           7.50          9.940   
13                  

In [4]:
dates = ['dd\mm\yyyy']
df1=df.sample(n=10,random_state=1)
print(df1)

                      Car_Name  Year  Selling_Price  Present_Price  \
285                       jazz  2016           7.40          8.500   
248                        i10  2013           4.00          4.600   
150         TVS Apache RTR 180  2011           0.50          0.826   
217                        eon  2016           3.15          4.430   
107  Royal Enfield Thunder 350  2013           1.25          1.500   
206                      xcent  2017           5.75          7.130   
132          Bajaj Avenger 220  2017           0.75          0.950   
73                  etios liva  2011           2.65          5.710   
288                       city  2015           8.40         13.600   
157          Yamaha FZ S V 2.0  2015           0.48          0.840   

     Kms_Driven Fuel_Type Seller_Type Transmission  Owner  
285       15059    Petrol      Dealer    Automatic      0  
248       30000    Petrol      Dealer       Manual      0  
150        6000    Petrol  Individual       Manua

In [5]:
dates = ['10-01-2004','11-01-2004','12-01-2004','13-01-2004','14-01-2004','15-01-2004','16-01-2004','17-01-2004','18-01-2004','19-01-2004']
df1=df.sample(n=10,random_state=1)
#df1['datesPurchased']=dates
print(df1)

                      Car_Name  Year  Selling_Price  Present_Price  \
285                       jazz  2016           7.40          8.500   
248                        i10  2013           4.00          4.600   
150         TVS Apache RTR 180  2011           0.50          0.826   
217                        eon  2016           3.15          4.430   
107  Royal Enfield Thunder 350  2013           1.25          1.500   
206                      xcent  2017           5.75          7.130   
132          Bajaj Avenger 220  2017           0.75          0.950   
73                  etios liva  2011           2.65          5.710   
288                       city  2015           8.40         13.600   
157          Yamaha FZ S V 2.0  2015           0.48          0.840   

     Kms_Driven Fuel_Type Seller_Type Transmission  Owner  
285       15059    Petrol      Dealer    Automatic      0  
248       30000    Petrol      Dealer       Manual      0  
150        6000    Petrol  Individual       Manua

In [6]:
df1['datePurchased']=dates
print(df1.to_string())

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner datePurchased
285                       jazz  2016           7.40          8.500       15059    Petrol      Dealer    Automatic      0    10-01-2004
248                        i10  2013           4.00          4.600       30000    Petrol      Dealer       Manual      0    11-01-2004
150         TVS Apache RTR 180  2011           0.50          0.826        6000    Petrol  Individual       Manual      0    12-01-2004
217                        eon  2016           3.15          4.430       15000    Petrol      Dealer       Manual      0    13-01-2004
107  Royal Enfield Thunder 350  2013           1.25          1.500       15000    Petrol  Individual       Manual      0    14-01-2004
206                      xcent  2017           5.75          7.130       12479    Petrol      Dealer       Manual      0    15-01-2004
132          Bajaj Avenger 220  2017           0.75    

In [9]:
df1["datesPurchased"]=dates
print(df1.to_string())

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner datePurchased datesPurchased
285                       jazz  2016           7.40          8.500       15059    Petrol      Dealer    Automatic      0    10-01-2004     10-01-2004
248                        i10  2013           4.00          4.600       30000    Petrol      Dealer       Manual      0    11-01-2004     11-01-2004
150         TVS Apache RTR 180  2011           0.50          0.826        6000    Petrol  Individual       Manual      0    12-01-2004     12-01-2004
217                        eon  2016           3.15          4.430       15000    Petrol      Dealer       Manual      0    13-01-2004     13-01-2004
107  Royal Enfield Thunder 350  2013           1.25          1.500       15000    Petrol  Individual       Manual      0    14-01-2004     14-01-2004
206                      xcent  2017           5.75          7.130       12479    Petrol      Dealer

In [10]:
df.to_excel("output.xlsx")
pd.read_excel("output.xlsx")

,Unnamed: 0,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,0,ritz,2014,3.35,5.590,27000,Petrol,Dealer,Manual,0
1,1,sx4,2013,4.75,9.540,43000,Diesel,Dealer,Manual,0
2,2,ciaz,2017,7.25,9.850,6900,Petrol,Dealer,Manual,0
3,3,wagon r,2011,2.85,4.150,5200,Petrol,Dealer,Manual,0
4,4,swift,2014,4.60,6.870,42450,Diesel,Dealer,Manual,0
5,5,vitara brezza,2018,9.25,9.830,2071,Diesel,Dealer,Manual,0
6,6,ciaz,2015,6.75,8.120,18796,Petrol,Dealer,Manual,0
7,7,s cross,2015,6.50,8.610,33429,Diesel,Dealer,Manual,0
8,8,ciaz,2016,8.75,8.890,20273,Diesel,Dealer,Manual,0
9,9,ciaz,2015,7.45,8.920,42367,Diesel,Dealer,Manual,0


In [18]:
df.to_excel("output.xlsx")

In [15]:
newParsedDates=pd.read_excel("output.xlsx",parse_dates=[10])

In [16]:
newParsedDatesColumnName=pd.read_excel("output.xlsx",parse_dates=["datesPurchased"])

In [17]:
newParsedDatesColumnName

,Unnamed: 0,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,datePurchased,datesPurchased
0,285,jazz,2016,7.40,8.500,15059,Petrol,Dealer,Automatic,0,10-01-2004,10-01-2004
1,248,i10,2013,4.00,4.600,30000,Petrol,Dealer,Manual,0,11-01-2004,11-01-2004
2,150,TVS Apache RTR 180,2011,0.50,0.826,6000,Petrol,Individual,Manual,0,12-01-2004,12-01-2004
3,217,eon,2016,3.15,4.430,15000,Petrol,Dealer,Manual,0,13-01-2004,13-01-2004
4,107,Royal Enfield Thunder 350,2013,1.25,1.500,15000,Petrol,Individual,Manual,0,14-01-2004,14-01-2004
5,206,xcent,2017,5.75,7.130,12479,Petrol,Dealer,Manual,0,15-01-2004,15-01-2004
6,132,Bajaj Avenger 220,2017,0.75,0.950,3500,Petrol,Individual,Manual,0,16-01-2004,16-01-2004
7,73,etios liva,2011,2.65,5.710,43000,Petrol,Dealer,Manual,0,17-01-2004,17-01-2004
8,288,city,2015,8.40,13.600,34000,Petrol,Dealer,Manual,0,18-01-2004,18-01-2004
9,157,Yamaha FZ S V 2.0,2015,0.48,0.840,23000,Petrol,Individual,Manual,0,19-01-2004,19-01-2004


In [3]:
data={
    "calories": [420,300,390], "duration" : [50,40,45]}
df=pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       300        40
2       390        45


In [4]:
print(df.loc(0))
print(df.iloc(0))
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64


In [5]:
df.iloc?

Type:        property
String form: <property object at 0x000002B3C990B330>
Docstring:  
Purely integer-location based indexing for selection by position.

.. deprecated:: 2.2.0

   Returning a tuple from a callable is deprecated.

``.iloc[]`` is primarily integer position based (from ``0`` to
``length-1`` of the axis), but may also be used with a boolean
array.

Allowed inputs are:

- An integer, e.g. ``5``.
- A list or array of integers, e.g. ``[4, 3, 0]``.
- A slice object with ints, e.g. ``1:7``.
- A boolean array.
- A ``callable`` function with one argument (the calling Series or
  DataFrame) and that returns valid output for indexing (one of the above).
  This is useful in method chains, when you don't have a reference to the
  calling object, but would like to base your selection on
  some value.
- A tuple of row and column indexes. The tuple elements consist of one of the
  above inputs, e.g. ``(0, 1)``.

``.iloc`` will raise ``IndexError`` if a requested indexer is
out-of-bound

In [6]:
df.loc?

Type:        property
String form: <property object at 0x000002B3C98DADE0>
Docstring:  
Access a group of rows and columns by label(s) or a boolean array.

``.loc[]`` is primarily label based, but may also be used with a
boolean array.

Allowed inputs are:

- A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
  interpreted as a *label* of the index, and **never** as an
  integer position along the index).
- A list or array of labels, e.g. ``['a', 'b', 'c']``.
- A slice object with labels, e.g. ``'a':'f'``.

  .. warning:: Note that contrary to usual python slices, **both** the
      start and the stop are included

- A boolean array of the same length as the axis being sliced,
  e.g. ``[True, False, True]``.
- An alignable boolean Series. The index of the key will be aligned before
  masking.
- An alignable Index. The Index of the returned selection will be the input.
- A ``callable`` function with one argument (the calling Series or
  DataFrame) and that returns valid output f

In [30]:
print(df.iloc[0,1])
print(df.iloc[2,1])

50
45


In [31]:
print(df.iloc[0:1,0:1])

   calories
0       420


In [37]:
print(df.loc[[0, 1][0]])

calories    420
duration     50
Name: 0, dtype: int64


In [40]:
df.to_json(orient='split')

'{"columns":["calories","duration"],"index":[0,1,2],"data":[[420,50],[300,40],[390,45]]}'

In [45]:
pd.to_json(orient='index')

AttributeError: module 'pandas' has no attribute 'to_json'

In [46]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    "datesPurchased": ["2024-02-03", "2025-04-09", "2023-08-15"],
    "car_model": ["Honda", "Toyota", "Ford"],
    "price": [20000, 25000, 18000]
})

# Convert DataFrame to JSON string with orient='index'
json_str = df.to_json(orient='index')

# Print JSON string
print(json_str)


{"0":{"datesPurchased":"2024-02-03","car_model":"Honda","price":20000},"1":{"datesPurchased":"2025-04-09","car_model":"Toyota","price":25000},"2":{"datesPurchased":"2023-08-15","car_model":"Ford","price":18000}}


In [50]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6,]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)



0
1
2
3


In [52]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print("2nd element on the First row:",arr[0,1])

2nd element on the First row: 2


In [54]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print("last element on the second row:",arr[-1,-1])

last element on the second row: 10


In [56]:
np.zeros?


Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [57]:
np.ones?


Signature: np.ones(shape, dtype=None, order='C', *, device=None, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In thi

In [58]:
np.full?

Signature:
np.full(
    shape,
    fill_value,
    dtype=None,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     ``np.array(fill_value).dtype``.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
     

In [59]:
np.inf?

Type:        float
String form: inf
Docstring:   Convert a string or number to a floating-point number, if possible.

In [60]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [61]:
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,12])
newarr = arr.reshape(4,3)
print(newarr)

ValueError: cannot reshape array of size 11 into shape (4,3)

In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,3)
print(newarr)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [8]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(-1))

[1 2 3 4 5 6 7 8]


In [14]:
mean=(81+85+99+84+87+88+111+86+103+87+94+78+77)/13

print(mean)

89.23076923076923


In [16]:
import numpy 
speed=(81,85,99,84,87,88,111,86,103,87,94,78,77)
x=numpy.median(speed)
print(x)

87.0
