# Day 10 – Mixed Practice (NumPy + Pandas): 10 Questions

## Question 1
### Using NumPy, create a 5×5 array with values 1–25.
#### Convert to DataFrame with columns `C1`–`C5`.
#### Print first and last 2 rows.

In [2]:
import numpy as np
import pandas as pd

In [3]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
df=pd.DataFrame(arr,columns=['C1','C2','C3','C4','C5'])
df

,C1,C2,C3,C4,C5
0,1,2,3,4,5
1,6,7,8,9,10
2,11,12,13,14,15
3,16,17,18,19,20
4,21,22,23,24,25


In [5]:
df.head(2)

,C1,C2,C3,C4,C5
0,1,2,3,4,5
1,6,7,8,9,10


In [6]:
df.tail(2)

,C1,C2,C3,C4,C5
3,16,17,18,19,20
4,21,22,23,24,25


## Question 2
### Use NumPy random to create 1D array of 10 integers between 0 and 100.
#### Convert to Series.
#### Print values greater than the Series mean.

In [7]:
arr=np.random.randint(0,101,size=10)
arr

array([39, 70, 46,  3, 30, 23, 51, 71, 81, 32], dtype=int32)

In [8]:
series=pd.Series(arr)
series

0    39
1    70
2    46
3     3
4    30
5    23
6    51
7    71
8    81
9    32
dtype: int32

In [12]:
series.mean()

np.float64(44.6)

In [9]:
series[series>series.mean()]

1    70
2    46
6    51
7    71
8    81
dtype: int32

## Question 3
### Create Celsius temperatures `[25, 30, 28, 22, 26]` as NumPy array.
#### Convert to Fahrenheit using vectorized operations.
#### Put in DataFrame with `celsius`, `fahrenheit`.

In [13]:
c=np.array([25,30,28,22,26])
c

array([25, 30, 28, 22, 26])

In [14]:
f=c*9/5+32

In [16]:
df=pd.DataFrame({'celsius':c,'fahrenheit':f})
df

,celsius,fahrenheit
0,25,77.0
1,30,86.0
2,28,82.4
3,22,71.6
4,26,78.8


## Question 4
### Create DataFrame `id`, `maths`, `science`, `english`.
#### Use NumPy to compute row-wise total and average marks.
#### Add them as new columns.

In [17]:
df = pd.DataFrame({
    'id': [1, 2, 3],
    'maths': [80, 70, 90],
    'science': [75, 85, 95],
    'english': [78, 88, 92]
})

In [20]:
df['total']=df[['maths','science','english']].sum(axis=1)
df

,id,maths,science,english,total
0,1,80,75,78,233
1,2,70,85,88,243
2,3,90,95,92,277


In [22]:
df['avg']=df['total'].mean()

In [23]:
df

,id,maths,science,english,total,avg
0,1,80,75,78,233,251.0
1,2,70,85,88,243,251.0
2,3,90,95,92,277,251.0


## Question 5
### Create 3×3 NumPy array of random integers.
#### Convert to DataFrame with custom row and column labels.
#### Print DataFrame.

In [25]:
np.random.seed(1)
arr=np.random.randint(1,10,size=(3,3))
arr

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]], dtype=int32)

In [27]:
df=pd.DataFrame(arr,columns=['c1','c2','c3'],index=['r1','r2','r3'])
df

,c1,c2,c3
r1,6,9,6
r2,1,1,2
r3,8,7,3


## Question 6
### Create DataFrame with `score`.
#### Use `np.where` to create `grade`: `"A"` (score≥80), `"B"` (50–79), `"C"` (<50).

In [29]:
df=pd.DataFrame({'score': [45, 82, 60, 30]})
df

,score
0,45
1,82
2,60
3,30


In [30]:
df['grade']=np.where(df['score']>=80,'A',np.where(df['score']>=50,'B','C'))

In [31]:
df

,score,grade
0,45,C
1,82,A
2,60,B
3,30,C


## Question 7
### Create 1D NumPy array of 12 values, reshape to 3×4, convert to DataFrame.
#### Add column with row sum.
#### Filter rows where sum > 15.

In [32]:
arr=np.arange(0,12).reshape(3,4)

In [33]:
df=pd.DataFrame(arr)
df

,0,1,2,3
0,0,1,2,3
1,4,5,6,7
2,8,9,10,11


In [34]:
df['row_sum']=df.sum(axis=1)
df

,0,1,2,3,row_sum
0,0,1,2,3,6
1,4,5,6,7,22
2,8,9,10,11,38


In [35]:
filter=df[df['row_sum']>15]
filter

,0,1,2,3,row_sum
1,4,5,6,7,22
2,8,9,10,11,38


## Question 8
### Create DataFrame with `age`.
#### Use `pd.cut` to create age groups.
#### Use `value_counts` to show counts per group.

In [37]:
df = pd.DataFrame({'age': [15, 22, 35, 42, 67]})
df['age_group'] = pd.cut(
    df['age'],
    bins=[0, 18, 35, 60, 100],
    labels=['0-18', '19-35', '36-60', '60+']
)

In [38]:
df['age_group'].value_counts()

age_group
19-35    2
0-18     1
36-60    1
60+      1
Name: count, dtype: int64

## Question 9
### Create NumPy array of floats.
#### Convert to Series.
#### Round to 2 decimals and store in another Series

In [39]:
arr = np.array([1.2345, 2.3456, 3.9876])

In [42]:
series=pd.Series(arr)

In [44]:
r_series=series.round(2)
r_series

0    1.23
1    2.35
2    3.99
dtype: float64

## Question 10
### Create small DataFrame and NumPy boolean mask for a condition on one column.
#### Use mask to filter DataFrame.

In [45]:
df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [10, 20, 30, 40]})

In [49]:
mask=np.array(df['y']>=20)
mask

array([False,  True,  True,  True])

In [51]:
filter=df[mask]
filter

,x,y
1,2,20
2,3,30
3,4,40
